# Generated by Django 4.1.5 on 2023-01-11 01:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bus_name', models.CharField(default='', max_length=25)),
                ('bus_number', models.CharField(default='', max_length=30)),
                ('driver_name', models.CharField(default='', max_length=50)),
                ('onward_date', models.DateField()),
                ('return_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='BusStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.CharField(choices=[('RAIPUR', 'RAIPUR'), ('AMBIKAPUR', 'ambikapur')], max_length=20)),
                ('destination', models.CharField(choices=[('RAIPUR', 'RAIPUR'), ('AMBIKAPUR', 'ambikapur')], max_length=20)),
                ('price', models.IntegerField()),
                ('time', models.FloatField()),
                ('total_time', models.FloatField()),
                ('bus_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.busdetails')),
            ],
        ),
    ]
