# Generated by Django 4.1.5 on 2023-01-11 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='busstop',
            name='destination',
            field=models.CharField(choices=[('RAIPUR', 'RAIPUR'), ('AMBIKAPUR', 'AMBIKAPUR')], max_length=20),
        ),
        migrations.AlterField(
            model_name='busstop',
            name='origin',
            field=models.CharField(choices=[('RAIPUR', 'RAIPUR'), ('AMBIKAPUR', 'AMBIKAPUR')], max_length=20),
        ),
    ]
