# Generated by Django 4.1.5 on 2023-01-12 01:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_alter_busstop_destination_alter_busstop_origin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('gender', models.CharField(choices=[('Mr', 'mr'), ('Mrs', 'mrs'), ('Ms', 'ms')], max_length=10)),
                ('age', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Booking',
            },
        ),
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bus_name', models.CharField(choices=[('volvo', 'volvo'), ('mahindra', 'mahindra')], max_length=25)),
                ('bus_number', models.CharField(default='', max_length=30)),
                ('driver_name', models.CharField(default='', max_length=50)),
                ('seats', models.IntegerField()),
                ('available', models.BooleanField(default=True)),
                ('onward_date', models.DateField()),
                ('return_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('route_id', models.AutoField(primary_key=True, serialize=False)),
                ('location_from', models.CharField(choices=[('Delhi', 'Delhi'), ('Jaipur', 'Jaipur'), ('Ajmer', 'Ajmer')], max_length=255)),
                ('location_to', models.CharField(choices=[('Ajmer', 'Ajmer'), ('Chandigarh', 'Chandigarh'), ('Delhi', 'Delhi')], max_length=255)),
                ('price', models.IntegerField()),
                ('time', models.FloatField()),
                ('total_time', models.FloatField()),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.bus')),
            ],
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('seat_number', models.IntegerField()),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.bus')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_id', models.CharField(blank=True, max_length=255)),
                ('created', models.DateTimeField(auto_now=True)),
                ('modified', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.booking')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.RemoveField(
            model_name='busstop',
            name='bus_details',
        ),
        migrations.DeleteModel(
            name='BusDetails',
        ),
        migrations.DeleteModel(
            name='BusStop',
        ),
        migrations.AddField(
            model_name='booking',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.route'),
        ),
    ]
